CREATE TABLE facts (id INTEGER PRIMARY KEY AUTOINCREMENT,fact TEXT);
INSERT INTO facts (id,fact) VALUES ("1","The earliest known use of cryptography is found in non-standard hieroglyphs carved into monuments from Egypt's Old Kingdom about 4500+ years ago.");
INSERT INTO facts (id,fact) VALUES ("2","Al-Kindi, an Arab Iraqi mathematician, invented the frequency analysis technique for breaking substitution ciphers (e.g. cryptograms) around 800 AD.");
INSERT INTO facts (id,fact) VALUES ("3","Edgar Allan Poe wrote an ad to a Philadelphia newspaper asking people to send him ciphers to crack. He solved them all.");
INSERT INTO facts (id,fact) VALUES ("4","Alan Turing, the British man who cracked the Nazi's Enigma encryption machines, commited suicide after being convicted for indecency for being gay.");
INSERT INTO facts (id,fact) VALUES ("5","Today everyone has access to the same open source encryption technology that governments and corporations use.");
INSERT INTO facts (id,fact) VALUES ("6","Whitfield Diffie, one of the people who invented public key encryption, didn't start reading until he was 10 years old.");
INSERT INTO facts (id,fact) VALUES ("7","David Kahn's 1,000 page book, The Codebreakers, is the definitive history of cryptography.");
INSERT INTO facts (id,fact) VALUES ("8","Steven Levy's book, Crypto, tells the story of how cypherpunks fought the NSA and legalized encryption for the masses.");
INSERT INTO facts (id,fact) VALUES ("9","The NSA operated as a multi-billion dollar organization for years before any government document acknowledged that it existed.");
INSERT INTO facts (id,fact) VALUES ("10","People joke that the NSA stands for No Such Agency. It really stands for National Security Agency.");
INSERT INTO facts (id,fact) VALUES ("11","In 1961, when most people had never heard of the NSA, two NSA cryptographers defected to the USSR and held a press conference about their experience.");
INSERT INTO facts (id,fact) VALUES ("12","The NSA tried (unsuccessfully) to prevent David Kahn's history of cryptography, The Codebreakers, from getting published.");
INSERT INTO facts (id,fact) VALUES ("13","'Human ingenuity cannot concoct a cipher which human ingenuity cannot resolve.' - Edgar Allen Poe");
INSERT INTO facts (id,fact) VALUES ("14","In 1795 Thomas Jefferson invented the Jefferson Disk encryption machine, which he called a wheel cipher.");
INSERT INTO facts (id,fact) VALUES ("15","In 1991, the NSA tried (unsuccessfully) to stop Microsoft from making a business deal with RSA Data Security to prevent millions of home users from using strong crypto.");
INSERT INTO facts (id,fact) VALUES ("16","Phil Zimmerman, inventor of PGP, was once arrested at an anti-nuclear rally alongside Ellsberg and Carl Sagan.");
INSERT INTO facts (id,fact) VALUES ("17","In 1991, Joseph Biden (head of the Senate Judiciary Committee at the time) pushed for an antiterrorism bill that would make encryption without government backdoors illegal in the US.");
INSERT INTO facts (id,fact) VALUES ("18","PGP, Pretty Good Privacy, is an email encryption program originally designed as a freeware human rights tool.");
INSERT INTO facts (id,fact) VALUES ("19","Grateful Dead lyricist John Perry Barlow was one of the founders of the digital civil liberties watchdog the Electronic Frontier Foundation (EFF).");
INSERT INTO facts (id,fact) VALUES ("20","'Cypherpunks know that a widely dispersed system can't be destroyed.' - the cypherpunk manifesto");
INSERT INTO facts (id,fact) VALUES ("21","During the entire Clinton administration, Al Gore fought against strong encryption without government backdoors.");
INSERT INTO facts (id,fact) VALUES ("22","Netscape developed the Secure Sockets Layer (SSL) protocol for their browser Navigator in the mid-nineties, so that people could securely use the world wide web.");
INSERT INTO facts (id,fact) VALUES ("23","Microsoft's operating systems included weak 40-bit encryption keys until year 2000 when US export laws were changed, making it legal to export strong crypto.");
INSERT INTO facts (id,fact) VALUES ("24","Phil Zimmerman was under investigation by a grand jury for three years for releasing the email encryption program PGP.");
INSERT INTO facts (id,fact) VALUES ("25","Until 1999, encryption technology in the US was considered a weapon and exporting it without a license was considered illegal arms dealing.");
INSERT INTO facts (id,fact) VALUES ("26","The RSA encryption algorithm is named after it's inventors: Ron Rivest, Adi Shamir, and Leonard Adleman");
INSERT INTO facts (id,fact) VALUES ("27","It takes about 5 minutes for anyone with a laptop to crack WEP encryption on wireless networks. Use WPA instead.");
INSERT INTO facts (id,fact) VALUES ("28","When coming up with encryption passphrases, length is most important. It's better to use a 15-word sentence than 15 random characters.");
INSERT INTO facts (id,fact) VALUES ("29","Be careful when using a public wifi network. If any part of the websites you login to don't use HTTPS, it's possible for someone to hijack your account.");
INSERT INTO facts (id,fact) VALUES ("30","'If privacy is outlawed, only outlaws will have privacy.' - Phil Zimmerman");
INSERT INTO facts (id,fact) VALUES ("31","'Relying on the government to protect your privacy is like asking a peeping tom to install your window blinds.' - John Perry Barlow");
INSERT INTO facts (id,fact) VALUES ("32","Simple substitution ciphers (e.g. cryptograms) should not be used to keep real secrets hidden. Use strong crypto software instead.");
INSERT INTO facts (id,fact) VALUES ("33","It's rumored that the bite mark in Apple's logo is a nod to the British cryptographer Alan Turing, who commited suicide by eating an apple laced with cyanide.");
